CREATE DATABASE FITNESS360;
USE FITNESS360;
CREATE TABLE MEMBER(
 M_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 FNAME VARCHAR(20),
 LNAME VARCHAR(20),
 PHONE_NO VARCHAR(15),
 EMAIL VARCHAR(30),
 DOB DATE,
 GENDER CHAR(1),
 SSN VARCHAR(15),
 ADDRESS VARCHAR(50)
);
CREATE TABLE LOCKER(
 LOCKER_ID INT NOT NULL PRIMARY KEY,
 M_ID INT,
 FOREIGN KEY (M_ID) REFERENCES MEMBER(M_ID)
 on delete set null
 on update cascade
);
CREATE TABLE SPORT(
 SNAME VARCHAR(15) NOT NULL PRIMARY KEY,
 TIMING VARCHAR (30),
 NUMCOURTS INT
);
CREATE TABLE COURT_ENTRY(
 CE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 M_ID INT,
 SPORT_NAME VARCHAR(15),
 TIME_IN DATETIME,
 TIME_OUT DATETIME,
 FOREIGN KEY (M_ID) REFERENCES MEMBER(M_ID)
 on delete cascade
 on update cascade,
 FOREIGN KEY (SPORT_NAME) REFERENCES SPORT(SNAME)
 on delete no action
 on update no action
);

CREATE TABLE GYM_ENTRY(
 GE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 M_ID INT,
 TIME_IN DATETIME,
 TIME_OUT DATETIME,
 FOREIGN KEY (M_ID) REFERENCES MEMBER(M_ID)
 on delete no action
 on update no action
);
CREATE TABLE GYM_EQUIPMENT(
 EQUIP_NAME VARCHAR(100) NOT NULL PRIMARY KEY,
 COMPANY_NAME VARCHAR(25),
 QUANTITY INT
);
CREATE TABLE EMPLOYEE(
 E_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 SSN VARCHAR(15),
 FNAME VARCHAR(25),
 LNAME VARCHAR(25),
 DOB DATE,
 SALARY VARCHAR(25),
 ADDRESS VARCHAR(100),
 PHONE_NO VARCHAR(20),
 EMAIL_ID VARCHAR(30)
);
CREATE TABLE COACH(
 C_ID INT PRIMARY KEY,
 TIMINGS VARCHAR(30),
 SNAME VARCHAR(15),
 FOREIGN KEY (SNAME) REFERENCES SPORT(SNAME)
 on delete set null
 on update cascade,
 FOREIGN KEY (C_ID) REFERENCES EMPLOYEE(E_ID)
 on delete cascade
 on update cascade
);
CREATE TABLE TRAINER(
 T_ID INT PRIMARY KEY,
 TIMINGS VARCHAR(30),
 ROOM_NO VARCHAR(20),
 FOREIGN KEY (T_ID) REFERENCES EMPLOYEE(E_ID)
 on delete cascade
 on update cascade
);

CREATE TABLE TRAINS(
 T_ID INT,
 M_ID INT,
 primary key(T_ID,M_ID),
 FOREIGN KEY (T_ID) REFERENCES TRAINER(T_ID)
 on delete cascade
 on update cascade,
 FOREIGN KEY (M_ID) REFERENCES MEMBER(M_ID)
 on delete cascade
 on update cascade
);
